name: Generate and publish article

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For pushing to repo
      packages: read   # For pulling container images
    steps:
      - uses: actions/checkout@v4
        with:
          # Required for pushing back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Make script executable and run
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          chmod +x ./scripts/generate_and_publish.sh
          ./scripts/generate_and_publish.sh
