name: Generate and publish article

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Required for pushing back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Make script executable and run
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./scripts/generate_and_publish.sh
          ./scripts/generate_and_publish.sh
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger_hugo
